name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: whoami

      # - name: Debug envs
      #   env:
      #     SERVER_HOST: ${{ secrets.SERVER_HOST }}
      #   run: |
      #     echo "HOST: ${{ secrets.SERVER_HOST }}"
      #     echo "USER: ${{ secrets.SERVER_USER }}"
      #     echo "1 USER: $SERVER_HOST"

      # - name: SSH Deploy
      #   uses: garygrossgarten/github-action-ssh@0.7.0
      #   with:
      #     command: echo "Conectado!"
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

          

      # - name: Clone repositório
      #   uses: actions/checkout@v3

      # - name: Build Docker image
      #   run: docker build -t meuapp:latest .

      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     script: |
      #       docker stop meuapp || true
      #       docker rm meuapp || true
      #       docker rmi meuapp || true
      #       cd /home/kali/Projects/curriculo-app
      #       git pull origin main
      #       docker build -t meuapp:latest .
      #       docker run -d --name meuapp -p 3000:3000 meuapp:latest
